server:
  port: 0

spring:
  application:
    name: item-service
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@oracle:1522:XE
    username: SHOP_ITEMS
    password: shopItems1234

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:com/example/itemservice/**/mapper/*Mapper.xml
  type-aliases-package: com.example.itemservice.vo
