spring:
  application:
    name: api-gateway-service
# Routing 설정
  cloud:
    circuitbreaker:
      resilience4j:
        enabled: true
    gateway:
      server:
        webflux:
          routes:
          # 각 서비스들의 actuator를 호출하기 위한 route 작성.
          # /user-service/actuator/health ==> USER-SERVICE/actuator/health
          - id: user-service-actuator
            uri: lb://USER-SERVICE
            predicates:
            - Path=/user-service/actuator/**
            filters:
            - RewritePath=/user-service/actuator/(?<segment>.*), /actuator/$\{segment}
          - id: order-service-actuator
            uri: lb://ORDER-SERVICE
            predicates:
            - Path=/order-service/actuator/**
            filters:
            - RewritePath=/order-service/actuator/(?<segment>.*), /actuator/$\{segment}
          - id: item-service-actuator
            uri: lb://ITEM_SERVICE
            predicates:
            - Path=/item-service/actuator/**
            filters:
            - RewritePath=/item-service/actuator(?<segment>.*), /actuator/$\{segment}
          - id: first-service
            predicates:
            - Path=/first-service/**
            uri: lb://FIRST-TEST-API-SERVICE
            filters:
            - AddRequestHeader=f-request, 202606101531
            - AddResponseHeader=api-response, token value
          - id: second-service
            predicates:
            - Path=/second-service/**
            uri: lb://SECOND-TEST-API-SERVICE
            filters:
            - AddRequestHeader=s-request, 202606101531
            - AddResponseHeader=api-response, token value
          - id: user-service-login
            uri: lb://USER-SERVICE
            predicates:
            - Path=/user-service/login
            filters:
            - RewritePath=/user-service/login, /login
          - id: user-service-regist
            uri: lb://USER-SERVICE
            predicates:
            - Path=/user-service/users
            - Method=POST
          - id: user-service
            predicates:
            - Path=/user-service/**
            filters:
            - AuthorizationHeaderFilter            
            - name: CircuitBreaker
              args:
                name: gatewayCircuitbreaker
                fallbackUri: forward:/fallback/failure
            uri: lb://USER-SERVICE
          - id: item-service
            predicates:
            - Path=/item-service/**
            filters:
            - name: CircuitBreaker
              args:
                name: gatewayCircuitbreaker
                fallbackUri: forward:/fallback/failure
            uri: lb://ITEM-SERVICE
          - id: order-service
            predicates:
            - Path=/order-service/**
            filters:
            - AuthorizationHeaderFilter
            - name: CircuitBreaker
              args:
                name: gatewayCircuitbreaker
                fallbackUri: forward:/fallback/failure
            uri: lb://ORDER-SERVICE
              
# CircuitBreaker 정책 설정
resilience4j:
  timelimiter:
    configs:
      default:
        timeout-duration:  4s
        cancel-running-future: false
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        #모니터링 중인 Request, Response가 50% 이상 실패하면 circuitbreaker를 오픈        
        failure-rate-threshold: 50
        # circuitbreaker open 유지시간 설정 (10000ms => 10s)
        wait-duration-in-open-state: 10000
        # circuitbreaker가 모니터링 할 request, response의 단위
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
    instances:
      gatewayCircuitBreak:
        base-config: default
server:
  port: 8000