spring:
  application:
    name: api-gateway-service
# Routing 설정
  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: first-service
            predicates:
            - Path=/first-service/**
            uri: lb://FIRST-TEST-API-SERVICE
            filters:
            - AddRequestHeader=f-request, 202606101531
            - AddResponseHeader=api-response, token value
          - id: second-service
            predicates:
            - Path=/second-service/**
            uri: lb://SECOND-TEST-API-SERVICE
            filters:
            - AddRequestHeader=s-request, 202606101531
            - AddResponseHeader=api-response, token value
          - id: user-service-login
            uri: lb://USER-SERVICE
            predicates:
            - Path=/user-service/login
            filters:
            - RewritePath=/user-service/login, /login
          - id: user-service-regist
            uri: lb://USER-SERVICE
            predicates:
            - Path=/user-service/users
            - Method=POST
          - id: user-service
            predicates:
            - Path=/user-service/**
            filters:
            - AuthorizationHeaderFilter            
            uri: lb://USER-SERVICE
          - id: item-service
            predicates:
            - Path=/item-service/**
            uri: lb://ITEM-SERVICE
          - id: order-service
            predicates:
            - Path=/order-service/**
            filters:
            - AuthorizationHeaderFilter
            uri: lb://ORDER-SERVICE
              

server:
  port: 8000
  
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaltZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    
token:
  secret: very-long-long-user-token-secret-202507101234